### ISSUE TITLE
Record classes result in an exception

### ISSUE THREAD

**Issue by martinmladenov** [SERG-Delft/andy#116]
Using Java 14 `record` classes results in the following exception:
```
Status: Done
*** ERROR ***
Something unexpected just happened. Please forward this message to the teacher.

java.lang.NullPointerException: Cannot invoke "nl.tudelft.cse1110.andy.config.RunConfiguration.weights()" because the return value of "nl.tudelft.cse1110.andy.execution.Context.getRunConfiguration()" is null
	at nl.tudelft.cse1110.andy.result.ResultBuilder.build(ResultBuilder.java:263)
	at nl.tudelft.cse1110.andy.execution.ExecutionFlow.run(ExecutionFlow.java:46)
	at nl.tudelft.cse1110.andy.Andy.run(Andy.java:54)
	at nl.tudelft.cse1110.andy.AndyOnWebLab.main(AndyOnWebLab.java:29)

Test score: -1/-1


```

**Comment by mauricioaniche** [comment]
Why should we support records ?

the exception in the configuration file, is this the place you tried records?

**Comment by martinmladenov** [comment]
No, this appears when students try to define a record class inside their solution. We use Java 14, which does support records, but for some reason Andy crashes when records are used. It's a very strange bug since the RunConfiguration should never be null, and in any case a record should not be able to make it null since it's just a language construct.
