### ISSUE TITLE
Ignore spaces at the ends of lines in the MetaTest StringReplacementEvaluator

### ISSUE THREAD

**Issue by martinmladenov** [SERG-Delft/andy#156]
`MetaTest.withStringReplacement` should ignore spaces not only at the beginning of lines but also at the end.

With the following library code:
```
      if (nums == null) {
          return false;
    }
```
and meta test:
```
                MetaTest.withStringReplacement("the nums is null",
                        """
                        if (nums == null) {
                          return false;
                        }
                        """,
                        "")
```
If there is a space after “{”, it will return an error:
```
java.lang.RuntimeException: Meta test failed to find this text replacement:
if (nums == null) {
  return false;
}
```
When the space is removed, it works properly.

**Comment by AntoniosBarotsis** [comment]
It might be simpler to just remove any spaces that are not inside a string for this. If not then [`trim`](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#trim--) would do what you're doing minus the regex.

**Comment by Una865** [comment]
I would like to work on this one :)

**Comment by mauricioaniche** [comment]
All yours, @Una865 ! @martinmladenov any comments on this one?

**Comment by martinmladenov** [comment]
I think this should be quite straightforward. We already do the same for leading spaces so implementing the same behaviour for trailing spaces should be quite similar.
