### ISSUE TITLE
When running meta tests, we should skip Jacoco

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/andy#202]
When running the meta tests, we don't need to instrument the code. The `RunConfiguration` already has a boolean `skipJacoco`, which makes the `InstrumentCodeForCoverageStep` to not do anything. We have to make sure this is set to true during meta tests (see `LibraryMetaTest`).

**Comment by cashbreaker** [comment]
I would like to work on this one

**Comment by mauricioaniche** [comment]
All yours, @cashbreaker!

**Comment by mauricioaniche** [comment]
This issue doesn't exist. When running meta tests, we only add `Run JUnit` in the list of steps to be executed, so coverage isn't even there.
