### ISSUE TITLE
In exam mode, delete rubrics

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/andy#203]
We deleted the Security Manager. We need new security measures. Although during the exam, rubrics are never there, it's best to be safe for other teachers that use Andy.

Suggestion: If Andy is running in exam mode, we should then:
* Delete the configuration file from the image
* Replace the classloader with a default `RunConfiguration` so that the old one can't be accessed via reflection

This can be done as an extra step. We can maybe also repurpose `ReplaceClassLoaderStep` for this.

**Comment by martinmladenov** [comment]
A simpler idea would be to delete part of the .java file directly. We could perhaps use comments for that. For example, we could have comments such as `// START DELETE` and `// END DELETE` and a step in Andy to delete everything between those two lines before compilation. Or perhaps we could do something more advanced and parse the raw `.java` file, remove the methods, and write it back.

**Comment by mauricioaniche** [comment]
We have to load the file first to see if it's exam mode, don't we, @martinmladenov ?

After we load the file, and we see it's exam, then, we gotta delete the file (no need to keep the file, we don't even need the weights) and remove the loaded configuration completely from the classpath.

**Comment by mauricioaniche** [comment]
Closed by #217
