### ISSUE TITLE
Meta test that subtracts points

### ISSUE THREAD

**Issue by martinmladenov** [SERG-Delft/andy#209]
Sometimes we want a meta test that doesn't give points if the student got it right, but subtracts points from the students that got it wrong.

This is similar to code checks that subtract points in #168

**Comment by puctom** [comment]
I want to work on this one

**Comment by mauricioaniche** [comment]
Great, @puctom. Please drop a message in our internal channel, so we know who you are :)

@martinmladenov any extra tips to @puctom on this one? You implemented something similar to code checks, maybe you have some nice lessons learned?

**Comment by martinmladenov** [comment]
I'd advise you to look into PR #210 since it does something very similar. I think the easiest way to implement this would be to make a separate step which runs those meta tests (while of course being careful not to introduce duplicated code).

**Comment by FrancescoHamar** [comment]
Hello! Could I also be assigned to this one as we would work together on it?
