### ISSUE TITLE
Make pipeline to work on Windows

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/andy#218]
It seems we have a failure when running in Windows. Apparently when deleting the temporary directory we create during the tests.

See logs: https://github.com/cse1110/andy/actions/runs/5327003222/jobs/9649801907?pr=217

I'm disabling Windows for now.

**Comment by martinmladenov** [comment]
@alexcojocaru2002 Can you comment here so that I can assign you to the issue?

**Comment by alexcojocaru2002** [comment]
Done 👍

**Comment by martinmladenov** [comment]
Unable to reproduce (see #263)
