### ISSUE TITLE
Make Docker tests work in forks/pull requests

### ISSUE THREAD

**Issue by martinmladenov** [SERG-Delft/andy#220]
Currently Docker assignment tests only run on pushes, not on pull requests.

Furthermore, the Dockerfile has the repo URL hardcoded. This causes it to break when it runs in a fork, as commits in forks are not present in the upstream repo. The URL should default to this one but it should be set in the CI via environment variables. GitHub provides such environment variables which we can use.

**Comment by Arraying** [comment]
I no longer have permissions to assign issues, can I take this one? :)

**Comment by martinmladenov** [comment]
Of course :)
