### ISSUE TITLE
Better Selenium integration tests

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/andy#221]
Our Selenium integration tests are quite poor. We gotta improve it.

One idea would be to use the exercises from previous exams here, so we have more real tests.

**Comment by sandemiroren1** [comment]
Hello, as usual me and kiril (@Zakrok09 ) would like to work on this one, but we are bit confused on what we are supposed to do but the issue seems interesting nonetheless :D

**Comment by mauricioaniche** [comment]
Hey, @sandemiroren1, I think we actually don't need more Selenium tests. In another ticket, people are working on the zip/unzip thing, and we have the assignments test that run all selenium assignments already! I'm closing this ticket.

**Comment by sandemiroren1** [comment]
@mauricioaniche ah glad to hear :)
