### ISSUE TITLE
Test doubles (assignment: readingProgress) code checks do not recognize verification

### ISSUE THREAD

**Issue by Fo3nix** [SERG-Delft/andy#222]
![WhatsApp Image 2023-06-24 at 08 24 09](https://github.com/SERG-Delft/andy/assets/97182469/9597e7a2-be26-469b-bd88-6e54c259a0e2)

As seen on the image, I verified for a specific action, and then also verified that no other methods were called for the mocks, including the emailService. The code checks say that there need to be verifications for all of the possible methods in the emailService, which was done. The answer provided does this by checking each method individually with times(1) or never(). 
My answer should also be a valid way to check methods called.

**Comment by mauricioaniche** [comment]
As we spoke via email, this isn't a bug in Andy! The rubrics are expecting three calls to this verify, which doesn't happen in the solution code!
