### ISSUE TITLE
Fix repository references

### ISSUE THREAD

**Issue by martinmladenov** [SERG-Delft/andy#224]
In various places in the repo we use the old repository URL (`cse1110/andy`) instead of the new one (`SERG-Delft/andy`). We should fix that, as the old one will stop working at some point.

**Comment by Zakrok09** [comment]
Hello!

@sandemiroren1 and I would like to work on this issue.

**Comment by martinmladenov** [comment]
Sure, I assigned you to the issue. GitHub doesn't let me assign @sandemiroren1 though, since he didn't comment on the issue.

**Comment by sandemiroren1** [comment]
@martinmladenov it should be fixed now :D
