### ISSUE TITLE
Add code check for if a method is invoked

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/andy#228]
We have a code check that looks if a method was invoked inside a test. We need another one that looks for method invocations anywhere.

**Comment by sandemiroren1** [comment]
Hello, me and Kiril would also like to work on this one as well.

**Comment by mauricioaniche** [comment]
@sandemiroren1 great! What's Kiril's github id?

**Comment by Zakrok09** [comment]
Hello, I am Kiril!

**Comment by Zakrok09** [comment]
Sir, shall we open a new branch ourselves, or should we wait for a branch that is tied to this issue? Thanks!
![image](https://github.com/SERG-Delft/andy/assets/31936449/dbe79ae3-2160-40d4-9868-623160f36ace)
