### ISSUE TITLE
New code check if class is used

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/andy#229]
Code check that looks whether the class is used in the student's solution. We can consider that the class is used if it's instantiated, or if a method (static or not) is called.

**Comment by sandemiroren1** [comment]
Hello, me and Kiril discussed and decided we would like to work on this one together.

**Comment by mauricioaniche** [comment]
It's yours.

**Comment by Zakrok09** [comment]
Hello, @sandemiroren1 and I will start working on this issue now. May I also be assigned?

**Comment by sandemiroren1** [comment]
If the method call can be anywhere then I believe it is complete.

**Comment by mauricioaniche** [comment]
I wrote a small comment there, asking for one extra test.
