### ISSUE TITLE
Exam mode configuration always enables Pitest and JaCoCo

### ISSUE THREAD

**Issue by martinmladenov** [SERG-Delft/andy#244]
PR #217 introduced an exam mode security guard which creates a copy of the configuration and discards the original one in order to prevent students from leaking meta tests or code checks during exams (in case the teacher forgets to remove them). This new configuration is supposed to be the same as the original, with the exception of meta tests and code checks. However, the current one has a bug: the `skipJacoco` and `skipPitest` methods aren't overridden, so they always return false, causing Pitest and JaCoCo to always be enabled during exams.

**Comment by alexcojocaru2002** [comment]
I can maybe work on this one ? @martinmladenov

**Comment by martinmladenov** [comment]
Sure, I'll assign you

**Comment by alexcojocaru2002** [comment]
@martinmladenov I don't exactly understand one thing : in the security guard, the skipJacoco / skipPitest methods should be overriden and return a certain value or their behavior should be inherited from somewhere else ?

**Comment by martinmladenov** [comment]
@alexcojocaru2002 Their behaviour should be inherited from the original run configuration, like with most other methods in the exam mode run configuration.

**Comment by alexcojocaru2002** [comment]
> @alexcojocaru2002 Their behaviour should be inherited from the original run configuration, like with most other methods in the exam mode run configuration.

So just taking the return value from the skipJacoco / skipPitest methods from the RunConfiguration and overriding the methods ?

**Comment by martinmladenov** [comment]
@alexcojocaru2002 Yes, exactly. It should be done in essentially the same way as everything else in that class.
