### ISSUE TITLE
Extra configuration for jqwik

### ISSUE THREAD

**Issue by mauricioaniche** [SERG-Delft/andy#246]
We should add the extra configuration `jqwik.maxdiscardratio.default = 2`. 

This will reduce the maximum discard ratio of JQWik. This will help us in quickly rejecting solutions that have bad data generation procedures.

(See #245 as this should also be implemented in pitest)

**Comment by Zakrok09** [comment]
Hello, sir! 

I would like to work on this.

**Comment by mauricioaniche** [comment]
It's yours!
