### ISSUE TITLE
Remove unnecessary check

### ISSUE THREAD

**Issue by martinmladenov** [SERG-Delft/andy#254]
Lines 75-77 of LibraryMetaTest.java have the following code:
```java
        if (metaFileContent.equals(originalLibraryContent)) {
            throw new RuntimeException("Meta test " + getName() + " failed to replace code.");
        }
```

This code doesn't do anything, as the meta file content is always a shifted version of the original, where all indentation is removed, so the exception will never be thrown. We already do a (proper) check for this in the StringReplacementEvaluator, so this check should be removed.

**Comment by adeelFeroz77** [comment]
Please assign me this issues. I want to contribute
